name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      uses: Eeems-Org/apt-cache-action@v1.3
      with:
        packages: libgl1-mesa-dev qt6-base-dev libgrpc++-dev
                  libgrpc-dev protobuf-compiler protobuf-compiler-grpc

    - name: Build
      run: |
        cmake -S . -B build
        cmake --build build -j $(getconf _NPROCESSORS_ONLN)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
